/* XPM */
static char *vt52[] = {
/* width height ncolors chars_per_pixel */
"64 48 142 2",

/* colors */

"   c #00",
" I c #01",
".x c #02",
" P c #03",
".z c #04",
" L c #05",
".l c #06",
" K c #07",
".k c #08",
" J c #09",
".j c #0A",
" H c #0B",
".h c #0C",
" G c #0D",
".g c #0E",
" F c #0F",
".f c #10",
" D c #11",
".d c #12",
" S c #13",
".s c #14",
" A c #15",
".a c #16",
" Z c #17",
".p c #18",
" C c #19",
".i c #1A",
" V c #1B",
".u c #1C",
" B c #1D",
".y c #1E",
" N c #1F",
".t c #20",
" M c #21",
".r c #22",
" m c #23",
".e c #24",
" n c #25",
".w c #26",
" b c #27",
".q c #28",
" v c #29",
".0 c #2A",
" c c #2B",
".9 c #2C",
" x c #2D",
".8 c #2E",
" z c #2F",
".7 c #30",
" l c #31",
".6 c #32",
" k c #33",
".5 c #34",
" j c #35",
".4 c #36",
" h c #37",
".3 c #38",
" g c #39",
".2 c #3A",
" f c #3B",
".1 c #3C",
" d c #3D",
".< c #3E",
" s c #3F",
"., c #40",
" a c #41",
".> c #42",
" p c #43",
".: c #44",
" i c #45",
".; c #46",
" u c #47",
".- c #48",
" y c #49",
".= c #4A",
" t c #4B",
".* c #4C",
" r c #4D",
".& c #4E",
" e c #4F",
".% c #50",
" w c #51",
".$ c #52",
" q c #53",
".# c #54",
" 0 c #55",
".@ c #56",
" 9 c #57",
".+ c #58",
" 8 c #59",
".O c #5A",
" 7 c #5B",
".o c #5C",
" 6 c #5D",
".X c #5E",
" 5 c #5F",
".. c #60",
" 4 c #61",
".  c #62",
" 3 c #63",
" | c #64",
" 2 c #65",
" } c #66",
" 1 c #67",
" { c #68",
" < c #69",
" [ c #6A",
" , c #6B",
" ] c #6C",
" > c #6D",
" ' c #6E",
" : c #6F",
" ` c #70",
" ; c #71",
" _ c #72",
" - c #73",
" ) c #74",
" = c #75",
" ( c #76",
" * c #77",
" / c #78",
" ^ c #7A",
" & c #7B",
" ~ c #7C",
" % c #7D",
" $ c #7F",
" ! c #80",
" # c #81",
" Q c #82",
" @ c #83",
" W c #84",
" + c #85",
" E c #86",
" O c #89",
" R c #8A",
" o c #8B",
" T c #8C",
" Y c #92",
" U c #96",
" X c #97",
" . c #A1",
".c c None",

/* pixels */
"                                               L F B.8.< y e 0 w.% w.% r t.= i.:.>.1 g.4 k.7.5 c n m.t.u.p.a A S F H J.l        ",
"                                   K.d.t.7.<.=.% w y f.0.i.h L L.l.k.j.h F D S Z.i.i.t x.< y.- l.7.5.3.3.2.,.- r r.;.-.o 7.p    ",
"                           Z.2 0 5.X 8.-.3 b.a J I                             I D.y m N D P                     I.x.z G.1 3.z  ",
"                        .r @ U . Y O # ' 3.. 8 q.>.2 k x b.t.i A.d G H K.l.z.x.h.1 j.w M.u.i.p C Z.s.d F.g H J L        .l.. F  ",
"                       I.+ e.X 3 , / % ^ % o R X T E W @ # % _ ` > [ < 6.#.$ t.= i.,.1.4 l.9 v v b.w.e.e.e.r m.e.u P     I.O B  ",
"                      .d 6.< = R 3.* y t.&.# q.+ 8 6 6 5 4.  4 | < { ; _ | > ' ^ : ' : : } 1 , , | 6 8.o.O e.e.x C.i      .>.0  ",
"                       k.; m D.7.;.o.=.y.t M m m.e.w v c.8.6.4 d.: y e 9 v j 0 7 7 8.o...X 3 3 1...o 5.  < <.<.s.l x I   P r h  ",
"                     I.*.e Z  .x.z N.$.0.w m n.w n n.w.q c.0 m.i D H.k m.e l F G D A.i N.e.0 z.6.5 g.,.-.$ g.s.w.x.5 L.x j ! u  ",
"                     G.%.d A       V.y              .x.z J.f.p.t b z.5.; b.0                          .x K.7.i v   j H v.6 2 8  ",
"                     b d F D     I.0 H                               L.7 b.w                               N m.q  .7.8 l.z 0 | P",
"                    .> M S G     K.0 I                                .9 b.r                              .t B v  .0.1.i  .: '.h",
"                   L.$.j.i.j    .s.r                                  .7.q B                              .e Z.q   m s.y  .1 = Z",
"                   A.* I.y K    .t Z                                .x.6.0 Z                               v S v.x.i i.e   u ^ n",
"                   x.3   N.z     b.h                                 L k c D                              .0.g.q.z D.*.q S 0.$ k",
"                   p.r I N.x  .x.9 L                                 J l.9.j                              .0 J v.l J r x.5 5.; s",
"                .x.$.g.z.u    .l c I                                 G.7.0 L                             I c.l v J P r.3.k N p y",
"                 G q P.k.i     H v                                   S z.0.x                            .x.9 P.q H  .% e L.i s e",
"                .t y  .h.p    .f.w                                   V.8 v I                            .z c I.e G   p 4.k A.,.%",
"                .4.4   D.a    .a.e                                   M.9.w                              .l.0   m F   K b F D i.&",
"                 y.r  .a.d    .u m                                  .w c.r                               J c   M.d     N.s.f.*.&",
"              .x.@.d  .i G    .u B                                   c c.y                               G.q   M A    .i Z v.3 t",
"               J 7 K   B J   I.t.e                                   l.9 C                              .f.e  .t C     A.r.>.i e",
"              .s.+ I  .y.z K Z.w.+ l V G P                         I.5 c S                              .s.t   B.u    .f.>.4 D.#",
"               m.$  .x.r.p.y A.,.3.g z 6 l.8 v.d K P               P.4 c G                              .p B  .i B     G 4.s.t i",
"              .6 y  .x c.p.e i z I.p.= C.j.* f f.o.$ x.q z B Z.s S Z.1.9.k                              .u C  .p M    .k h I f.0",
"            .j 2.*.0.u n c.#.5 K.y.-.d P.2.9   M.+ M.k.6.% V.t 9 f.4.:.8.z                               M.a   A m        .j.$.j",
"           F.X.+ z ) ! 1 T ,.<.% 1.0 B y.5.z.h p B   A.;.j   v f I D j.8                                 m D  .d m        .5 a  ",
"        .a 3 w.q.% 5 # ( % & ( + [ 8 ; < f.1 4 f.a.u.=.s  .a.;.k  .p d 6 z N.d.j.z                       n G   F n      .z. .p  ",
"      .t { t.= ( : ( @ ^ _ Q ` ; ; > ( , ` ( = 0 r ;.& b.9.o.t     B., 2 0 9.#.%.:.2 c.u D.j.z          .q.j   G.w       v 2.x  ",
"     v <.< y ` _ 5 o ( ^ % ; W ` ( ` & ' ' ( > ) { _ } | ' :.-.r.a.4 l p M.r.q k.,.& 0 9 0 r.<.5.q.i.f.j.9 K  .j b     I 7 k    ",
" P h , z.l b u.6.# / _ - $ - $ = { $ [ @ : O ] = [ > ( = = 2 -.  ( [ 6 `. .# w.1.8.e.t M.0 g i e.# 0.% 8.o P  .k v    .a , H    ",
" d.X.<.f L   I.g.#.:.,.-.O 2 ] ~.  * 1 - ' : ~ 1 / > E | {.. { 4 ^ [ 5.-.+.. : ' : , 3 9 p k.q.r M.w z.=.X I  .k z I  .: y      ",
".X i i.- s k m C x n.e n b z j.> u 9.X ] 1 ] # 6 ' } 2 { ; | !.@ | 3.+ l.2 7 ; 1.@ }.X * 1 * }.X 8.= g.1 a     K z   H. .u      ",
" {.r A.u b.3 i u.> f.6 c b b.w n.w.q.7.2.- e } 0 >.% ;...# % , h g.X.- K.& [ _ { ) [ [ 1 6 5 Z S.w.2 t 8 f.r.k J.8   x 9.z      ",
" a q.0.0 m.i.s.p.e.6.2.,.> f l.0.w.w.e b b.0 x i 4.3.  c.* ] 7 {.+ }.t.9 9 2 } 5 ).. *.@ 1 f          .z G M x D v L.@ j        ",
" L p k.g.f.y c c m C D.d.u.0.3 s.,.2.6.9.q.e n.5.t L G.s c h.,.*.=.2.p e.# ].$ > 9 ].o.& 5.h               J k N V.r 2.g        ",
"   J.>.$ f.w.s.j.g C n c n.i.d.f.p n k d.>.<.4 x.i.h P      .l.g V.f p.1.&.& 8 9.@ 1.> ] z                 B.e.0.h.@ d          ",
"       J C.8.,.;.1.0.a H.h.a.e.0 b B.s F.s.t.8.2.< d h.9.y D.l    .f.>.0 v.1 ] i _ q q.$ G               I z C v.t [ H          ",
"               K Z c d.: s.8.i.h H.s m.0.q.t A G F.i v j d.,.2.7.e C.p.u.r k.* a }.5 0.6                .g.9 M.i 9.1            ",
"                       L S b f u i.6.u G.j.d M v c.e Z G G Z n.6 d a.1 j.q B.a.i v.e.1 K                .e V.9 n -.j            ",
"                               P D.e.3.; p.4.y.g J.d N v.9.w C.g.h A M.7.2 s f.5.0.y.d.l I            .z l.a.w.O.,              ",
"                                      .x.g.r j.: u.3.e.d.j.f.u.q x b.i F H D.u.0 h d.1.3 z m A.j.x     Z v.e v <.j              ",
"                                               I.h B k p.; g.q.s.j.g C.w.8.q B D H.g C.q h.2 s f.5.w m.6.d x.: j                ",
"                                                        .k.p x d p d x C.h.h.p n.9 v.t.s H H.a.e k.1 s v z.0 e.k                ",
"                                                                .l.s v g p.,.8 C G.j.s M.0 c.r A H J.d V D k.0                  ",
"                                                                        .z D.e j p.:.5 N.g.j D.y.0.8 b.u.5.O.l                  ",
"                                                                                .x.g.t j p.; h.r D.h Z.9 0 M                    ",
"                                                                                         I.g M.3 r.%.&.-.y                      "
};
